# Deploying mta in a namespace
:toc:

## Overview
This example shows how to a single MTA multiple times in a space using namespaces.

## Requirements
* Installed MultiApps CF CLI Plugin v2.5.0 or above

## Official documentation
* SAP Help Portal: link:https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/b28fd77836d44bde8c404618bf0f1228.html[(Experimental) Namespaces]

## Deploying two applications in namespace
Checkout the repository and navigate to 'cf-mta-examples/namespace/two-modules'

### 1 Components of this deployment 
The files included there are the following
* hello.mtar - the MTA archive we'll be deploying, a package of the other files ready for deployment 
* backend.war - sample java web application, included outside the archive for easy access
* mtad.yaml - the mta deployment descriptor, included outside the archive for easy access
The war we're deploying contains two simple servlets - one (the 'backend') returning the 'message' environment variable as a GET response on path /content, and the other (the 'router') calling the backend (accessed through 'backend' environment variable) and forwarding it's response on path /hello. These are modeled in the mtad.yaml descriptor:
```yaml
...        
  - name: hello-backend
    type: java.tomee
    path: backend.war
    provides:
      - name: backend
        properties:
          url: "https://${routes/0/route}" #exposing the backend route 
    parameters:
...
    properties:
      message: "Hello, from ${app-name}!" #assigning the message we want returned from the backend
...
  - name: hello-router
    type: java.tomee
    path: backend.war
    requires:
      - name: backend
        properties:
          backend: ~{url} #using the route provided from the backend and persisting it an environment variable in the router
          name: backend
...

```
Make note of the route assignment in the descriptor:
```yaml
...
      routes:
        - route:  ${app-name}.${default-domain} #adding the ${app-name} parameter to the host of the deployed application; this ensures no route conflicts
...

```

### 2 Deploy 
To deploy the mta initially simply execute:
```bash
  $ cf deploy ./hello.mtar
  
```
### 3 Verify the created applications and mta details
```bash
  $ cf a
  $ cf mtas
  $ cf mta hello
  
```
### 4 Deploy a second time using a namespace
```bash
  $ cf deploy ./hello.mtar --namespace foo
  
```
### 5 Verify that the applications have not replaced the old deployment
```bash
  $ cf a
  $ cf mtas
  $ cf mta hello --namespace foo
  
```
### 6 Make manual calls to the exposed web endpoints to validate different deployments
Executing the following should return two different messages, depending on which version of the application is beind called. The urls are dependent on your default domain nad can be seen in the result of the 'cf a' or 'cf mta hello' command
```bash
  $ cf a | grep '^hello-router'
  $ curl https://<url-of-hello-router>/hello
  Hello, from hello-backend!
  $ cf a | grep '^foo-hello-router'
  $ curl https://<url-of-foo-hello-router>/hello
  Hello, from foo-hello-backend!
  
```

## Deploying an application and a service, namespace applied to only 1 of them
Checkout the repository and navigate to 'cf-mta-examples/namespace/module-and-service-with-apply-flag'.

The steps here can be repeted as above, the notable difference is that in this descriptor, the 'apply-namespace' parameter is used:
```yaml
...
  - name: hello-service
    type: auditlog
    parameters:
      apply-namespace: false #overriding default value 'true'
...

```
Using this parameter ensures that the service will be unique in the space even across multiple deployments in different namespaces. If you deply the archive in two namespaces consecutively the service instance will only be instantiated once.

NOTE: It can be applied to any module or resource in the descriptor - if used in the example with two modules (e.g. setting it false for hello-backend module) it will result in only 1 hello-backend application being created and replaced on a second deployment.
