# Deploying mta in a namespace
:toc:

## Overview
This example shows how to deploy a single MTA multiple times in a space using namespaces.

## Requirements
* Installed MultiApps CF CLI Plugin v2.5.0 or above

## Official documentation
* SAP Help Portal: link:https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/b28fd77836d44bde8c404618bf0f1228.html[Namespaces]

## Deploying two applications in namespace
Checkout the repository and navigate to 'cf-mta-examples/namespace/two-modules'

### 1 Components of this deployment 
The files included there are the following
* hello.mtar - the MTA archive we'll be deploying, a package of the other files ready for deployment 
* backend.war - sample java web application, included outside the archive for easy access
* mtad.yaml - the mta deployment descriptor, included outside the archive for easy access
The war we're deploying contains two simple servlets - one (the 'backend') returning the 'message' environment variable as a GET response on path /content, and the other (the 'router') calling the backend (accessed through 'backend' environment variable) and forwarding it's response on path /hello. These are modeled in the mtad.yaml descriptor:
```yaml
...        
  - name: hello-backend
    type: java.tomcat
    path: backend.war
    provides:
      - name: backend
        properties:
          url: "https://${routes/0/route}" #exposing the backend route 
    parameters:
...
    properties:
      message: "Hello, from ${app-name}!" #assigning the message we want returned from the backend
...
  - name: hello-router
    type: java.tomcat
    path: backend.war
    requires:
      - name: backend
        properties:
          backend: ~{url} #using the route provided from the backend and persisting it an environment variable in the router
          name: backend
...

```

### 2 Deploy 
To deploy the mta initially simply execute:
```bash
  $ cf deploy ./hello.mtar
  
```
### 3 Verify the created applications and mta details
```bash
  $ cf a
  $ cf mtas
  $ cf mta hello
  
```
### 4 Deploy a second time using a namespace
```bash
  $ cf deploy ./hello.mtar --namespace foo
  
```
### 5 Verify that the applications have not replaced the old deployment
```bash
  $ cf a
  $ cf mtas
  $ cf mta hello --namespace foo
  
```
### 6 Make manual calls to the exposed web endpoints to validate different deployments
Executing the following should return two different messages, depending on which version of the application is beind called. The urls are dependent on your default domain nad can be seen in the result of the 'cf a' or 'cf mta hello' command
```bash
  $ cf a | grep '^hello-router'
  $ curl https://<url-of-hello-router>/hello
  Hello, from hello-backend!
  $ cf a | grep '^foo-hello-router'
  $ curl https://<url-of-foo-hello-router>/hello
  Hello, from foo-hello-backend!
  
```

## Deploying an application and a service, namespace applied to only 1 of them
Checkout the repository and navigate to 'cf-mta-examples/namespace/module-and-service-with-apply-flag'.

The steps here can be repeted as above, the notable difference is that in this descriptor, the 'apply-namespace' parameter is used:
```yaml
...
  - name: hello-service
    type: auditlog
    parameters:
      apply-namespace: false #overriding default value 'true'
...

```
Using this parameter ensures that the service will be unique in the space even across multiple deployments in different namespaces. If you deply the archive in two namespaces consecutively the service instance will only be instantiated once.

NOTE: It can be applied to any module or resource in the descriptor - if used in the example with two modules (e.g. setting it false for hello-backend module) it will result in only 1 hello-backend application being created and replaced on a second deployment.

## Deploying an application, namespace applied to only 1 of the routes
Checkout the repository and navigate to 'cf-mta-examples/namespace/module-with-apply-flag-to-route'.

The steps are the same as previous examples, the difference is that 'apply-namespace' parameter is used inside module route map:
```yaml
...
 routes:
  - route: hello-backend.${default-domain}
  - route: route-without-namespace.${default-domain}
    apply-namespace: false
...

```
## Deploying with global namespace modifier parameter

To deploy an application with set global parameters, follow these steps:

### 1. Check out the repository and navigate to the 'cf-mta-examples/namespace/global-parameters' directory.
### 2. The deployment process is similar to previous examples, but there are new parameters for modifying namespace behavior globally and locally.

The global namespace parameters are defined as follows:
```
parameters:
  apply-namespace:
    app-names: true
    service-names: true
    app-routes: true
```

If you deploy with only these parameters, all applications, services, and routes are expected to have the namespace applied as a prefix, if one was provided.

If you add a namespace modifying parameter locally, for example:
```
modules:
  - name: hello-backend
    type: application
    path: appBits.zip
    parameters:
      apply-namespace: false
```
it means that the application named "hello-backend" will not have the namespace prefix. Locally applied namespace parameters have higher priority than global parameters.

The local `apply-namespace` parameter is set for one application/service/route, whereas global parameters are set on all applications/services/routes.

When you run the command:
```bash
$ cf deploy ./hello.mtar --namespace foo
```
the expected results are:
- hello-backend // local value is higher priority that global and global is ignored
- foo-hello-router // global value is applied
- route-without-namespace.${default-domain}
- foo-my-cf-service

Operation parameters/command-line options have the highest priority. If you use them, all applications/services/routes will follow the behavior specified in these command-line options and ignore all additional parameters, even if present.

When you run the command:
```bash
$ cf deploy ./hello.mtar --namespace foo --apply-namespace-app-names true --apply-namespace-service-names true --apply-namespace-app-routes true
```
all applications/services/routes will have the prefix `foo`. In this way, other parameters in the descriptor are ignored.

Similarly, when you run the command:
```bash
$ cf deploy ./hello.mtar --namespace foo --apply-namespace-app-names false --apply-namespace-service-names false --apply-namespace-app-routes false
```
none of the applications/services/routes will have the prefix `foo`.

## Deploying an application, namespace applied as suffix
### Configure using CLI flag
Checkout the repository and navigate to 'cf-mta-examples/namespace/module-with-apply-as-suffix-flag'.

The steps are the same as previous examples, the difference is that you add the _apply-namespace-as-suffix_ parameter:
``` bash
$ cf deploy ./hello.mtar --namespace foo --apply-namespace-as-suffix true
```
This will result in creating an application that has the namespace applied as a suffix and not a prefix.

### Configure using _as-suffix_ in the descriptor
Checkout the repository and navigate to 'cf-mta-examples/namespace/module-with-apply-as-suffix-global-parameter'. In this case where the namespace must be applied is configured using the global parameters in the deployment descriptor:
```yaml
...
 parameters:
  apply-namespace:
    as-suffix: true
...

```

The steps are the same as previous examples. Just run without the flag:
``` bash
$ cf deploy ./hello.mtar --namespace foo
```

This will result in creating an application that has the namespace applied as a suffix and not a prefix.