:toc:

# Metadata for properties and parameters

## Using metadata

Parameters and properties in a mta descriptor contain implicit metadata that can be altered and declared by the user.
There are 3 metadata elements for properties and parameters:

* `optional` - controls if the property/param can be left with a null value, default is `false`
* `overwritable` - controls if the property/param can be overwritten by an extension descriptor, default is `true`
* `sensitive` - controls if the property/param should be hidden in log files(e.g. ********), default is `false`

You can overwrite the data and metadata for a property/parameter in the descriptor using an extension descriptor. However any property or parameter that were defined as `overwritable: false` cannot be overwritten.
For more information, check out the link:https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/fca2cedcb79649e7a8f51234faea1142.html?locale=en-US[official documentation].

*Example 1* - define a property that cannot be modified outside of this descriptor:
```text
  - name: my-app
    type: application
..  
    properties:
      my-property: my-value
    properties-metadata:  
      my-property:  
        optional: false		# the property cannot be left without a value in the descriptor (this can be omitted, same as defaut)
	overwritable: false	# the property cannot be modified by an extension descriptor
```

*Example 2* - define an empty property that must be set in extension descriptor, otherwise the deployment will fail:
```text
  - name: my-app
    type: application
..  
    properties:
      my-property: 
    properties-metadata:  
      my-property:  
        optional: true 		# the property can be left without a value in the descriptor 
        overwritable: true 	# the property can be overwritten by a value in the extension descriptor (this can be omitted, same as defaut)
```

## Try it out

### Deploy the MTA

Deploy the example mta from this repo. The mta has an application `my-app` that has an empty parameter `null-parameter` and an empty property `null-property` defined.

```text
    parameters:
	  ...
      null-parameter: 
    parameters-metadata:  
      null-parameter:  
        optional: true 
        overwritable: true   
    properties:
      null-property: 
    properties-metadata:  
      null-property:  
        optional: true  
        overwritable: true  
```

``` bash
cf deploy ./test.mtar
```

Now check the deployed application's environment to see the property value

``` bash
$ cf env my-app
Getting env variables for app my-app in org deploy-service / space i356120 as ivan.kasarov@sap.com...
OK

System-Provided:
...
User-Provided:
null-property: null
...
```

### Re-deploy the MTA with an extension descriptor

This time the extension descriptor will set values to the empty parameter and property

```text
    parameters:
      null-parameter: extension-value
    properties:
      null-property: extension-value
```

``` bash
cf deploy ./test.mtar -e extension.yaml
```

Check the re-deployed application's new environment

``` bash
$ cf env my-app
Getting env variables for app my-app in org deploy-service / space i356120 as ivan.kasarov@sap.com...
OK

System-Provided:
...
User-Provided:
null-property: null
...
```
