# Keeping existing CF app service bindings during update
:toc:

## Overview
This example shows how to preserve manually created service bindings, during an MTA deployment, that are created outside of the MTA. A real use case for that is a multi-tenant scenario where bindings are created during tenant onboarding of a multitenant application, and those bindings are not maintained by MTA deployment. 

Modelled via a module level parameter `keep-existing` and parameter option `service-bindings`:
```bash 
modules:
  - name:...
    parameters:
      keep-existing: 
        service-bindings: true
```

## Official Documentation

* SAP Help Portal: link:https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/177d34d45e3d4fd99f4eeeffc5814cf1.html#loio177d34d45e3d4fd99f4eeeffc5814cf1__section_moduleSpecificParameters[Module-Specific Parameters]

NOTE: See link:mta.yaml[mta.yaml] or link:mtad.yaml[mtad.yaml] in the current directory.

## Try it out

### Initial deployment
In this part the MTA will initially be deployed with two applications and one service instance. However, there is no binding between them.

You can deploy it directly from an `mtad.yaml` file:

```bash
$ cf deploy ./ -f ;
```

Alternatively, you can build an MTAR archive from the `mta.yaml` file:

```bash
$ mbt build -p cf -t . ;
```

And then deploy the built MTAR archive:

```bash
$ cf deploy a.cf.app_0.0.0.mtar -f ;
```

### Manually bind service instance

Run the following commands:

```bash
$ cf bind-service cf-app-keeping-bindings dummy-service
$ cf bind-service cf-app-resetting-bindings dummy-service
```

#### Examine the result

To examine the result, run the following command:

```bash
$ cf services
Getting services in org ...
name           service       ... bound apps                                         ...  
dummy-service  user-provided     cf-app-keeping-bindings, cf-app-resetting-bindings                                    
```

### Re-deply to simulate update

```bash
$ cf deploy -f ;
```

or

```bash
$ cf deploy a.cf.app_0.0.0.mtar -f ;
```

#### Examine the result

Verify that  app `cf-app-keeping-bindings` has the binding preserved and app `cf-app-keeping-bindings` has lost the binding.

```bash
$ cf services
Getting services in org ...
name           service       ... bound apps                                         ...  
dummy-service  user-provided     cf-app-keeping-bindings                                     
```

## Undeploy the MTA
It is recommended to stop or undeploy your MTAs when they are no longer needed. In order to do so, run the following command:
``` bash
$ cf undeploy <mta-id> -f --delete-services
```
