:toc:

# Fine tuning service management handling

- With this tutorial you'll learn how to fine tune the deployment behavior of your mta when handling service creation or update. You can use the following two resource configurations:

    * `active:`` which tells the mta deplyoer to (or not-to) apply any actions to manage this resource. Default value is `active: true`
    * `optional:` which instructs the mta deployer to try and process the resource, but to ignore any errors which may occur and continue with the deployment of the other mta components. Such may be that a service offering is missing in that landscape, or the service creation/update failed. Default is `optional: false`


## Requirements
- Before you continue, you should check how CF services are described in the mta(d).yaml: TODO - link to tutorial
- the modelled resources require entitlements to an application-logging service of type lite

## [Optional] Oficial documemtation in Help SAP Portal
- link:https://help.sap.com/[Official Name of the page]

# Try out

## How to execute

### [Optional] Any alternatives for execution, e.g. `cf deploy xx.mtar` and `cf deploy folder/`

## Verify the result
- Check with CF natives
