:toc:

# Manage User-Provided Service Instances

User-provided service instances enable developers to use services that are not available in the marketplace with their apps running on Cloud Foundry.

The example will demonstrate how to manage User-Provided Service Instances with MTA.
Real use case for SAP Business Technology Platform Cloud Foundry environment where user-provided service are needed is Dynatrace service. With dynatrace you can monitor your application and get insights of it.

To create user-provided services, you need resource with type `org.cloudfoundry.user-provided-service`.
The resource has only one required parameter `config` that represents credentials of the service.


## Oficial documemtation in Help SAP Portal
- link:https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/37eedfdf814d4845ad784334d7ad6f8e.html[MTA Module Types, Resource Types, and Parameters for Applications in the Cloud Foundry Environment] -> Special Resource Types

# Try out

## Execute initial creation of user-provided service

The step represents the initial creation of service instance.

### Deploy with a deployment descriptor (mtad.yaml)

That approach uses deployment descritpr `link:mtad.yaml[mtad.yaml]` 

```bash
  $ cf deploy ./ -f
  ...
  Processing service "my-simple-service"...
  Creating service "my-simple-service" from MTA resource "my-simple-service"...
  Skipping deletion of services, because the command line option "--delete-services" is not specified.
  Process finished.
```

### Verify the result

```bash
  $  cf s
Getting services in org deploy-service / space i076083 as I076083...

name                 service            plan         bound apps    last operation     broker   upgrade available
my-simple-service    user-provided
```

## Execute update of user-provided service

The step represents the the update of service instance when it have changed parameters.

That approach uses deployment descritpr `link:mtad.yaml[mtad.yaml]` and extension descriptor `link:service-credentials.mtaext[service-credentials.mtaext]`:

```bash
  $  cf deploy ./ -e service-credentials.mtaext -f
  ...
  Uploading 1 files...
  ../create.service.example.mtar
  OK
  Uploading 1 files...
  ./service-credentials.mtaext
  OK
  ...
  Service "my-simple-service" exists but doesnt have any bound applications
  Processing service "my-simple-service"...
  Updating service "my-simple-service"...
```

NOTE: The service credential `foo` defined in deployment descriptor with value `baz` is overwritten with value `bar` coming from extension descriptor
