:toc:

# Deploying docker images as CF apps with an MTA

This example shows how to model a Cloud Foundry application, running a docker image, as an MTA. Cloud Foundry container runtime brings the capability to download docker images from a registry as dockerhub and to spin up containers from such. Those containers are managed just as regular Cloud Foundry apps.
Documentated in the CF docs: link:https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html[Deploying an App with Docker]

The actual image getting deployed is of a cf sample app written in go: https://github.com/cloudfoundry-samples/test-app.git


NOTE: See link:mtad.yaml[mtad.yaml] for up-to-date details on the attributes, environment and deployer parameters used.  See link:mta.yaml[mta.yaml] for up-to-date details on the required build parameters.


# Try it out

## Deploy an MTA containing a CF app referencing a docker image

The example demostrates 2 different approaches that lead to the same result.

### Deploy directly from directory
This approach uses deployment descritpr `mtad.yaml` :
```bash
$ cf deploy ./
Deploying multi-target app archive /Users/******/dev/repos/ds/cf-mta-examples/cf-app-docker/a.docker.cf.app.mtar in org ****** / space ****** as ******...
...
Deploying in org "deploy-service" and space "******"
Detected MTA schema version: "3"
Detected deployed MTA with ID "a.docker.cf.app" and version "0.0.0"
Detected new MTA version: "0.0.0"
Deployed MTA version: "0.0.0"
Adding domain "${domain}"...
Updating application "my-mta-managed-app"...
Uploading application "my-mta-managed-app"...
Stopping application "my-mta-managed-app"...
Starting application "my-mta-managed-app"...
Application "my-mta-managed-app" started and available at "${org}-${space}-${app-name}.${domain}"
...
Process finished.
```
### Or create an MTA archive and deploy it
To generate the MTA archive based on the design time MTA decriptor link:mta.yaml[mta.yaml] use the Cloud MTA Build tool link:https://sap.github.io/cloud-mta-build-tool/usage/#one-step-build['build'] command that creates the MTAR from the project sources:

```bash
mbt build

```

To generate the MTA archive based on the deployment time MTA decriptor link:mtad.yaml[mtad.yaml] use the Cloud MTA Build tool link:https://sap.github.io/cloud-mta-build-tool/usage/#how-to-build-an-mta-archive-from-the-modules-build-artifacts['assemble'] command that assembles the MTAR from already built binaries:

```bash
mbt assemble

```

Then use the newly generated MTAR for deployment.

```bash

cf deploy mta_archives/a.docker.cf.app_0.0.0.mtar ;

```

## Examine the result

### List the deployed MTA
```bash
$ cf mta a.docker.cf.app
Showing health and status for multi-target app a.docker.cf.app in org ****** / space ****** as ******...
OK
Version: 0.0.0

Apps:
name                 requested state   instances   memory   disk   urls
my-mta-managed-app   started           1/1         1G       1G     ${org}-${space}-${app-name}.${domain}
```

### List app status and attributes
```bash
$cf app my-mta-managed-app
Showing health and status for app my-mta-managed-app in org ****** / space ****** as ******...

name:              my-mta-managed-app
requested state:   started
routes:            ${org}-${space}-${app-name}.${domain}
stack:
docker image:      cloudfoundry/test-app:latest
```

### Test if the app is working
Find the route assigned to the app in the previous output (of `cf deploy`, `cf mta` or `cf app`)

- Directly open it in a browser as https://<route>

- Or execute a GET request from the command line
```bash
curl https://${org}-${space}-${app-name}.${domain}/index
0
echo $?
0
```

