:toc:

# Configure MTA with HANA services for Trial accounts

Normally, the one and the same MTA can be deployed in every account and SAP Cloud Deployment service does not set any limitations.
However, there are limitations based on the configured Entitlements in the account.

HANA Schemas and HDI Cntainers can be used when you have `hana` or `hanatrial` service in Cloud Foundry service marketplace. In the past, `hanatrial` was the only one possible service offering for Trial accounts. Now both `hana` and `hanatrial` are possible. 

NOTE: *March 2021*: Recommendation is to use `hana` service offering for Enterprise and Trial accounts. To make `hana` available in marketplace, you need `SAP HANA Cloud` and `SAP HANA Schemas & HDI Containers` entitlements. 

The tutorial is for everyone who already have configred Trial accounts and `hanatrial` is already avaiable in the marketplace. To make `hanatrial` available in new Trial accounts, you need to add entitlement `SAP HANA Schemas & HDI Containers Trial`

To enable deployment of the same MTA, you can use MTA extension descriptors.  Extension descriptors are complementary files to the main deployment descriptor that provide additional data. They have file extension `.mtaext` and are external for MTA archive `.mtar`. Extension descriptors can be used to provide deployment specific information, for example credentials to external services.

## Requirements
* Entitlement `Cloud Foundry Runtime`
* Entitlements for hana service plans:
** In Trial accounts:
*** *RECOMMENDED* `SAP HANA Cloud` and `SAP HANA Schemas & HDI Containers`
*** *NOT RECOMMENDED* `SAP HANA Schemas & HDI Containers Trial`


## Oficial documemtation in Help SAP Portal
- link:https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/50df803465324d36851c79fd07e8972c.html[Defining MTA Extension Descriptors]
- link:https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/9e34487b1a8643fb9a93ae6c4894f015.html#loio9e34487b1a8643fb9a93ae6c4894f015__section_mtaResourceTypes[Resources] -> MTA Resource Types
- link:https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/046f127f2a614438b616ccfc575fdb16.html[Trial Accounts]
- link:https://saphanajourney.com/hana-cloud/learning-article/starting-a-sap-hana-cloud-trial-when-you-have-an-existing-sap-cloud-platform-trial/[Starting your trial when you have an existing SAP Cloud Platform trial account]


# Try out

## Deploy MTAR with `hana`

The first step of the example, shows successful deployment of the MTA without extension descriptor. It will use the default behavior when using resource types `com.sap.xs.hana<xxx>`. These resource types by default are configured to use `hana` as a service offering.

### Deploy with a deployment descriptor (mtad.yaml)

That approach uses deployment descritpr `link:mtad.yaml[mtad.yaml]` and ready application binaries `link:appBits.zip[appBits.zip]`:


``` bash
$ cf deploy -f
...
Uploading 1 files...
  .../my-mta.mtar
OK
...
No deployed MTA detected - this is initial deployment
Detected new MTA version: "1.0.0"
Processing service "my-service"...
Creating service "my-service" from MTA resource "my-service"...
Creating application "my-app" from MTA module "my-app"...
Uploading application "my-app"...
Scaling application "my-app" to "1" instances...
Staging application "my-app"...
Application "my-app" staged
Starting application "my-app"...
...
```

### Verify the result

Check that app and service instance are created, and service has the service offering `hana`, which comes a  default value.

``` bash
$ cf s
...
name              service            plan             bound apps       last operation     ...
my-service        hana               schema             my-app           create succeeded   ...

$ cf a
...
name             requested state   instances   memory   disk   urls
my-app           started           1/1         1G       1G     ...
```

## Deploy MTAR with `hanatrial`

This step of the example shows how the MTA is deployed in Trial account where the goal is to use `hanatrial` service offering.

### Deploy with a deployment descriptor (mtad.yaml)

That approach uses deployment descritpr `link:mtad.yaml[mtad.yaml]`, ready application binaries `link:appBits.zip[appBits.zip]` and extension descriptor for DEV env `link:trial.mtaext[trial.mtaext]`:

``` bash
$ cf deploy -f -e trial.mtaext
...
Uploading 1 files...
  .../my-mta.mtar
OK
Uploading 2 files...
  .../trial.mtaext
OK
...
No deployed MTA detected - this is initial deployment
Detected new MTA version: "1.0.0"
Processing service "my-service"...
Creating service "my-service" from MTA resource "my-service"...
Creating application "my-app" from MTA module "my-app"...
Uploading application "my-app"...
Scaling application "my-app" to "1" instances...
Staging application "my-app"...
Application "my-app" staged
Starting application "my-app"...
...
```

### Verify the result

Check that app and service instance are created, and service has the service offering `hanatrial`, defined in the extension descriptor:

``` bash
$ cf s
...
name              service            plan             bound apps       last operation     ...
my-service        hanatrial          schema           my-app           create succeeded   ...

$ cf a
...
name             requested state   instances   memory   disk   urls
my-app           started           1/1         1G       1G     ...
```
